-- AlterTable
ALTER TABLE `history_transactions` MODIFY `status` ENUM('SUCCESS', 'FAILED', 'PENDING', 'PROCESSING', 'REFUND') NOT NULL DEFAULT 'PENDING';

-- AlterTable
ALTER TABLE `transactions` MODIFY `status` ENUM('SUCCESS', 'FAILED', 'PENDING', 'PROCESSING', 'REFUND') NOT NULL DEFAULT 'PENDING';
